
services:
  db:
    image: postgres:16
    restart: always
    container_name: postgresql
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - DATABASE_HOST=127.0.0.1
      - POSTGRES_DB=prod_star_db
      - POSTGRES_USER=mcarabies
      - POSTGRES_PASSWORD=29232436mjC*
    ports:
      - "5432:5432"
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admindb@productosestrella.site
      - PGADMIN_DEFAULT_PASSWORD=29232436mjC*
    ports:
      - "80:80"
    depends_on:
      - db
    
  web:
    build: .
    container_name: django
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=prod_star_db
      - POSTGRES_USER=mcarabies
      - POSTGRES_PASSWORD=29232436mjC*
    depends_on:
      - db
    