# Generated by Django 5.1.1 on 2024-09-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_about_linksocial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(max_length=250, null=True, verbose_name='Descripción'),
        ),
    ]
