# Generated by Django 5.1.1 on 2024-09-19 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_product_url_afiliado_amazon_product_url_amazon'),
    ]

    operations = [
        migrations.CreateModel(
            name='Productimages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(blank=True, max_length=350, null=True, verbose_name='Enlace')),
                ('alt', models.CharField(max_length=100, verbose_name='Descripción de la imagen (alt)')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Imagen',
                'verbose_name_plural': 'Imagenes',
                'ordering': ['product'],
            },
        ),
    ]
